disparity_node:
  ros__parameters:
    P1: 200.0
    P2: 400.0
    approximate_sync: true
    approximate_sync_tolerance_seconds: 0.001
    correlation_window_size: 27
    disp12_max_diff: 0
    disparity_range: 48
    image_transport: raw
    min_disparity: -20
    prefilter_cap: 31
    prefilter_size: 9
    qos_overrides./disparity.publisher.depth: 1
    qos_overrides./disparity.publisher.history: keep_last
    qos_overrides./disparity.publisher.reliability: reliable
    qos_overrides./left/camera_info.subscription.depth: 5
    qos_overrides./left/camera_info.subscription.history: keep_last
    qos_overrides./left/camera_info.subscription.reliability: best_effort
    qos_overrides./left/image_rect.subscription.depth: 5
    qos_overrides./left/image_rect.subscription.history: keep_last
    qos_overrides./left/image_rect.subscription.reliability: best_effort
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    qos_overrides./right/camera_info.subscription.depth: 5
    qos_overrides./right/camera_info.subscription.history: keep_last
    qos_overrides./right/camera_info.subscription.reliability: best_effort
    qos_overrides./right/image_rect.subscription.depth: 5
    qos_overrides./right/image_rect.subscription.history: keep_last
    qos_overrides./right/image_rect.subscription.reliability: best_effort
    queue_size: 5
    sgbm_mode: 0
    speckle_range: 4
    speckle_size: 500
    start_type_description_service: true
    stereo_algorithm: 0
    texture_threshold: 0
    uniqueness_ratio: 11.0
    use_sim_time: false
    use_system_default_qos: false
